### ISSUE TITLE
Implement product upload

### ISSUE THREAD

**Issue by Anjun-Feng** [JoyfulTechLauncher/joyfulfashionista_app_beta#117]
Implement product upload

**Comment by Qingyang0818** [comment]
Fix the error in product image upload, now, user can upload single image or mutiple images (max 5)
First, we can select the images we want to upload:

![屏幕截图 2023-09-30 004920](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/98dc014e-a6e7-4561-bb3b-6be9aad781d4)

After we click the upload, the program will print the new product id if successful, we can check that message to ensure we have already uploaded:


![屏幕截图 2023-09-30 005002](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/4495070b-4bb6-4514-b162-2b4ad179d714)

We can know this new product's id is 245, Check it in wordpress to ensure it:

![屏幕截图 2023-09-30 005238](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/4c7a5e0f-82b2-456d-849b-113485ef4290)

Here we can see the id is 245 has already been added to wordpress, next we check whether it has two images since we choose two when upload:

![屏幕截图 2023-09-30 005323](https://github.com/JoyfulTechLauncher/joyfulfashionista_app_beta/assets/67152451/47aef712-6a61-429b-88b3-777c47edf910)
 On the right corner, we can see all two images have been successfully uploaded. This part is fixed!

**Comment by Anjun-Feng** [comment]
Close as resolved
